config/routes.rb
Rails.application.routes.draw do
  get 'entries/create'
  root 'homes#index'
  devise_for :users
  resources :topics, only: [:index, :new, :create, :show] do
    resources :entries
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :entry, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_user_location!, if: :storable_location?
  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def create
    @entry = current_user.entries.new(entry_params)
    if @entry.save
      flash[:notice] = "応募完了しました"
      redirect_to @entry.topic, notice: "予約が完了しました"
    else
      flash[:alert] = "応募に失敗しました"
      redirect_to :back
    end
  end

  private

    def entry_params
      params.require(:entry).permit(:user_id, :topic_id, :messages)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: :show # ログインしているか調べるヘルパーメソッド, showは例外(except)
  def index
    @topics = Topic.all.includes(:user).where(user_id: current_user.id)
    @entries = Entry.all.includes(:user, :topic)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params) # topic_paramsの値が入ったオブジェクト作成
    image = Magick::ImageList.new('./public/base_image.png') # テキストを書き込むための画像を読み込む
    draw = Magick::Draw.new # 画像に線や文字を描画するDrawオブジェクト生成
    title = cut_text(@topic.title) # cut_textの処理結果を代入
    draw.annotate(image, 0, 0, 0, -120, title) do # 文字の描画(画像、幅、高さ、x座標、y座標、描画する文字)
      self.font = 'app/assets/NotoSansJP-Bold.otf' # 日本語対応可能なフォントにする
      self.fill = '#000' # フォントの塗りつぶし色
      self.gravity = Magick::CenterGravity # 描画基準位置(中央)
      self.font_weight = Magick::BoldWeight # フォントの太さ
      self.stroke = 'transparent' # フォントの縁取り色(透過)
      self.pointsize = 48 # フォントサイズ(48pt)
    end
    image_path = image.write(uniq_file_name).filename # uniq_file_nameメソッドの処理結果のファイル名を代入
    image_url = cut_path(image_path) # cut_textメソッドの処理結果をimage_urlに代入
    @topic.image_url = image_url # @topicに作成画像であるimage_urlを追加
    if @topic.save
      flash[:notice] = "トピックが保存されました"
      redirect_to @topic # Topic.newで作った＠topicへリダイレクト
    else
      flash[:alert] = "募集作成に失敗しました"
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @entries = Entry.where(topic_id: @topic)
  end

  private

    def topic_params # title,contentの受け取りを許可し、mergeでuser_idにcurrentuser.idを追加で受け取る
      params.require(:topic).permit(:title, :content).merge(user_id: current_user.id)
    end

    def cut_path(url) # /./public/以下を""に切り取る
      url.sub(/\.\/public\//, "")
    end

    def uniq_file_name # .public/ランダムな文字列/.pngというファイル名に加工する
      "./public/#{SecureRandom.hex}.png"
    end

    def cut_text(text) # 15文字ごとに改行入れる
      text.scan(/.{1,15}/).join("\n")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/entries/create.html.erb
<h1>Entries#create</h1>
<p>Find me in app/views/entries/create.html.erb</p>

app/views/homes/index.html.erb
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <h1 class="intro-lead-in h1">SNSを使って<br>簡単募集しよう</h1>
      <div class="intro-heading">Topic BoardはSNSで簡単に募集することができるサービスです。</div>
        <div class="intro-button">
          <%= link_to '今すぐ始める', new_topic_path, class: "btn btn-xl" %>
        </div>
      </div>
    </div>
  </div>
</header>
<section class="features-icons bg-2 text-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-g-3">
          <div class="features-icons-icon">
            <i class="far fa-comment" style="font-size: 80px;"></i>
          </div>
          <h3>SNSで簡単募集</h3>
          <p class="lead mb-0">SNS常にあなたの募集情報を投稿して<br>もっと手軽に人を集めましょう。</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
          <div class="features-icons-icon">
            <i class="far fa-image" style="font-size: 80px;"></i>
          </div>
          <h3>シェア画像も自動生成</h3>
          <p class="lead mb-0">募集タイトルと詳細を入力するだけで<br>SNS用の画像を作ってくれます。</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
          <div class="features-icons-icon">
            <i class="far fa-envelope" style="font-size: 80px;"></i>
          </div>
          <h3>無駄なやり取りなし</h3>
          <p class="lead mb-0">気に入った人にだけ返事をするので、<br>無駄なやりとりは発生しません。</p>
        </div>
      </div>
    </div>
  </div>
</section>
<footer class="footer bg-2">
  <div class="container text-center">
    <span class="text-muted">©️ y-k</span>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TopicBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= yield :ogp %>
      <meta http-equiv="content-type" content="text/html; charset=utf-8" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-2 navbar-light header">
      <div class="container">
        <a class="navbar-brand" href="/topics">Topic Board</a>
        <% if user_signed_in? %>
          <div class="my-2 my-lg-0">
            <%= link_to 'ログアウト', destroy_user_session_path, class: "no-text-decoration", method: :delete %>
          </div>
        <% end %>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script>
      //url-textを現在のURL（document.URL）に変更する
      $('.url-text').text(document.URL);

      //clipURL関数の定義（urlをコピーする機能）
      function clipURL() {
        //コピー用のtextareaを作成
        $('body').append('<textarea id="currentURL" style="position:fixed;left:-100%;">'+location.href+'</textarea>');
        
        //currentURLのIDを選択
        $('#currentURL').select();

        //選択しているテキストをクリップボードにコピーする
        document.execCommand('copy');

        //現在のcurrentURLのIDを削除
        $('#currentURL').remove();

        //アラートを表示する
        alert("URLをコピーしました。");
      }

      //textにcard-titleクラスのテキストを代入する
      var text = $('.card-title').text();

      //twitterurlのシェア用urlを作成してtwitterurlに挿入
      var twitterurl = "https://twitter.com/intent/tweet?url=" + document.URL + "&text=" + text + "&hashtags=#テックピット";

      //btn-twクラスのリンクをtwitterurlに変更する
      $('.btn-tw').attr('href',twitterurl);
    </script>
  </body>
</html>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/index.html.erb
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <h2 class="intro-lead-in h2">SNSで簡単募集しよう！</h2>
      <div class="intro-button">
        <%= link_to '今すぐ始める', new_topic_path, class: "btn btn-xl" %>
      </div>
    </div>
  </div>
</header>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-1">
      <div class="topic-show-left">
        <h2 class="topic-list-title"><%= current_user.email %>さんの募集一覧</h2>
        <ul class="list-group">
          <% @topics.each do |topic| %> <!-- トピック一覧表示 -->
            <%= link_to topic_path(topic), class: "no-text-decoration" do %>
              <li class="list-group">
                <div class="card">
                  <img class="card-img-bottom" src="/<%= topic.image_url %>" alt="">
                  <div class="card-body">
                    <h5 class="card-title"><%= topic.title %></h5>
                    <p class="card-text"><%= topic.content %></p>
                    <p class="card-text"><small class="text-muted"><%= topic.created_at.strftime('%Y/%m/%d %H:%M') %></small></p>
                  </div>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-4">
      <div class="topic-show-left">
        <h2 class="entry-list-title">新着応募</h2>
        <ul class="list-group">
          <% @entries.each do |entry| %>
            <% if entry.topic.user_id == current_user.id %> <!-- 自分の作成した募集へのエントリーの場合 -->
              <li class="list-group-item">
                <div><%= entry.topic.user.email %><small class="text-muted"><%= entry.topic.created_at.strftime('%Y/%m/%d %H:%M') %></small></div>
                <div class="list-group-item-comment">
                  <%= entry.messages %>
                </div>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container topics-new">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= form_with model: @topic do |f| %>
        <div class="form-group">
          <label for="exampleInputTitle">募集タイトル</label>
          <%= f.text_field :title, class: "form-control", placeholder: "募集タイトルを入力してください" %>
        </div>
        <div class="form-group">
          <label for="exampleInputDetail">募集内容詳細</label>
          <%= f.text_area :content, class: "form-control", placeholder: "例:Topic Boardを手伝ってくれる人を募集します！" %>
        </div>
        <div class="intro-button text-center">
          <%= f.submit "募集を作る", class: "btn btn-xl" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<% content_for :ogp do %>
  <meta property="og:title" content ="<%= @topic.title %>" />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="/topics/<%= @topic.id %>" />
  <meta property="og:image" content=<%= "#{root_url}#{@topic.image_url}" %> />
  <meta property="og:site_name"  content="Techpit_Job" />
  <meta property="og:description" content="<%= @topic.content %>" />
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@techpit_jp" />
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="job-show">
        <ul class="list-group">
          <li class="list-group">
            <div class="card">
              <img class="card-img-bottom" src="/<%= @topic.image_url %>" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title"><%= @topic.title %></h5>
                <p class="card-text"><%= @topic.content %></p>
                <p class="card-text"><small class="text-muted"><%= @topic.created_at.strftime('%Y/%m/%d %H:%M') %></small></p>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <div class="topic-show-share">
        <div class="social text-center">
          <a href="https://twitter.com/intent/tweet?url=http://techpit.jp&text=テックピット&hashtags=#techpit" rel="nofollow" class="btn btn-xl btn-tw" target="_blank">twitterに投稿</a>
        </div>
        <p class="share-url"><a onclick="clipURL()" class="url-text">URL</a><i class="far fa-copy"></i></p>
      </div>
      <% if user_signed_in? %> <!-- ログインしている場合 -->
        <% if @topic.user_id == current_user.id %> <!-- 自分の作成したトピックだった場合 -->
          <div class="topic-show-comment">
            <h2 class="topic-list-title">トピック一覧</h2>
            <ul class="list-group">
              <% @entries.each do |entry| %>
                <li class="list-group-item">
                  <div><%= entry.user.email %><small class="text-muted"><%= entry.created_at.strftime('%Y/%m/%d %H:%M') %></small></div>
                  <div class="list-group-item-comment">
                    <%= entry.messages %>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>
        <% else %> <!-- 自分の作成したトピックではない場合 -->
          <% if current_user.entries.where(topic_id: @topic.id).present? %>
            <div class="intro-button text-center">
              <a href="javascript:void(0)" class="btn btn-xl">すでに応募しています</a>
            </div>
          <% else %> <!-- まだ応募していない場合 -->
            <%= form_with model: [@topic, @topic.entries.new] do |f| %>
              <%= f.hidden_field :topic_id, value: @topic.id %>
              <div class="form-group form-message">
                <label for="exampleInputMessage">メッセージ（任意）</label>
                <%= f.text_area :messages, class: "form-control", placeholder: "例：興味あります。よろしければDMでご連絡お待ちしております。" %>
              </div>
              <div class="intro-button text-center">
                <%= f.submit "応募する", class: "btn btn-xl" %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% else %> <!-- ログインしていない場合 -->
        <div class="show-login text-center">
          <div class="intro-button text-center">
            <a href="/users/sign_in" class="btn btn-xl">応募する</a>
          </div>
          <p>応募するには会員登録・ログインの必要がございます</p>
        </div>
        <div class="topic-show-comment">
          <ul>
            <h2 class="topic-list-title">ご応募の流れ</h2>
            <p>1. 応募するとアカウント情報が相手に届きます。</p>
            <p>2. 必ず連絡が来るわけではありません。</p>
            <p>3. 募集者がマッチしたと思った場合メッセージを送ります。</p>
            <p>4. メッセージは連携SNSで届きます。</p>
            <p>* Twitterで応募した場合は『』で『全てのユーザーからダイレクトメッセージを受信する』にチェックを入れてください。</p>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>